from pathlib import Path

path = Path('index.html')
text = path.read_text(encoding='utf-8')

old_css = '''#sector-reveal{position:fixed;z-index:1;inset:0;overflow:hidden;pointer-events:none;opacity:0;isolation:isolate;--reveal-sector:var(--vision-teal)}.wrap{z-index:2}#sector-reveal::before{content:"";position:absolute;inset:auto -28% -48dvh;height:156dvh;background:radial-gradient(ellipse 78% 54% at 50% 88%,color-mix(in srgb,var(--reveal-sector),transparent 14%) 0%,color-mix(in srgb,var(--reveal-sector),transparent 43%) 31%,color-mix(in srgb,var(--reveal-sector),transparent 73%) 57%,transparent 77%),linear-gradient(to top,color-mix(in srgb,var(--reveal-sector),transparent 81%),transparent 72%);filter:blur(20px) saturate(118%);transform:translate3d(0,54%,0);opacity:0;will-change:transform,opacity}.sector-reveal-active{opacity:1}.sector-reveal-active::before{animation:sector-atmosphere-rise 1.38s cubic-bezier(.16,.72,.22,1) forwards}@keyframes sector-atmosphere-rise{0%{opacity:0;transform:translate3d(0,54%,0)}18%{opacity:.84;transform:translate3d(0,37%,0)}45%{opacity:.74;transform:translate3d(0,6%,0)}72%{opacity:.31;transform:translate3d(0,-23%,0)}100%{opacity:0;transform:translate3d(0,-50%,0)}}'''
new_css = '''#sector-reveal{position:fixed;z-index:3;inset:0;overflow:hidden;pointer-events:none;opacity:0;isolation:isolate;--reveal-sector:var(--vision-teal)}.wrap{z-index:2}#sector-reveal::before,#sector-reveal::after{content:"";position:absolute;display:block;pointer-events:none;will-change:transform,opacity}#sector-reveal::before{inset:auto -36% -58dvh;height:172dvh;background:radial-gradient(ellipse 70% 48% at 50% 85%,color-mix(in srgb,var(--reveal-sector),transparent 5%) 0%,color-mix(in srgb,var(--reveal-sector),transparent 30%) 30%,color-mix(in srgb,var(--reveal-sector),transparent 60%) 55%,transparent 78%),radial-gradient(ellipse 47% 38% at 18% 93%,color-mix(in srgb,var(--reveal-sector),transparent 35%),transparent 71%),radial-gradient(ellipse 47% 38% at 82% 93%,color-mix(in srgb,var(--reveal-sector),transparent 35%),transparent 71%);filter:blur(21px) saturate(127%);transform:translate3d(0,60%,0) scale(1,.8);opacity:0}#sector-reveal::after{inset:auto -25% -25dvh;height:132dvh;background:radial-gradient(ellipse 83% 56% at 50% 93%,color-mix(in srgb,var(--reveal-sector),transparent 51%) 0%,color-mix(in srgb,var(--reveal-sector),transparent 74%) 51%,transparent 79%),linear-gradient(to top,color-mix(in srgb,var(--reveal-sector),transparent 83%),transparent 68%);filter:blur(27px) saturate(116%);transform:translate3d(0,58%,0) scale(1,.85);opacity:0}.sector-reveal-active{opacity:1}.sector-reveal-active::before{animation:sector-vapor-rise 2.55s cubic-bezier(.15,.7,.19,1) forwards}.sector-reveal-active::after{animation:sector-vapor-bloom 2.55s .08s cubic-bezier(.18,.7,.22,1) forwards}@keyframes sector-vapor-rise{0%{opacity:0;transform:translate3d(0,62%,0) scale(1,.72)}13%{opacity:.93;transform:translate3d(0,44%,0) scale(1,.86)}39%{opacity:.85;transform:translate3d(0,7%,0) scale(1.08,1)}68%{opacity:.57;transform:translate3d(0,-27%,0) scale(1.18,1.08)}100%{opacity:0;transform:translate3d(0,-58%,0) scale(1.24,1.12)}}@keyframes sector-vapor-bloom{0%{opacity:0;transform:translate3d(0,59%,0) scale(1,.8)}17%{opacity:.52;transform:translate3d(0,42%,0) scale(1.08,.91)}49%{opacity:.48;transform:translate3d(0,3%,0) scale(1.2,1.04)}76%{opacity:.27;transform:translate3d(0,-25%,0) scale(1.25,1.1)}100%{opacity:0;transform:translate3d(0,-49%,0) scale(1.3,1.14)}}@media(max-width:600px){#sector-reveal::before{inset-inline:-48%;filter:blur(16px)}#sector-reveal::after{inset-inline:-38%;filter:blur(20px)}}'''
if old_css not in text:
    raise SystemExit('Current sector atmosphere CSS not found.')
text = text.replace(old_css, new_css, 1)

old_reduced = '''@media(max-width:600px){.gender-card{min-height:158px}.gender-illustration{transform:scale(.9)}.colorchoice{grid-template-rows:108px auto;min-height:170px}.swatch{min-height:108px}}@media(prefers-reduced-motion:reduce){#sector-reveal{background:radial-gradient(ellipse 85% 48% at 50% 100%,color-mix(in srgb,var(--reveal-sector),transparent 52%),transparent 74%);transition:opacity .01ms linear}.sector-reveal-active{opacity:.9}.sector-reveal-active::before{animation:none;opacity:.74;transform:translate3d(0,0,0)}.tap-ripple{width:40px;height:40px}.tap-ripple .press-wave{animation:none;opacity:.55;transform:scale(.8)}.tap-ripple .press-spark{display:none}.gender-card,.colorchoice{transition:none}}'''
new_reduced = '''@media(max-width:600px){.gender-card{min-height:158px}.gender-illustration{transform:scale(.9)}.colorchoice{grid-template-rows:108px auto;min-height:170px}.swatch{min-height:108px}}@media(prefers-reduced-motion:reduce){#sector-reveal{background:radial-gradient(ellipse 95% 43% at 50% 100%,color-mix(in srgb,var(--reveal-sector),transparent 38%),transparent 75%);transition:opacity .01ms linear}.sector-reveal-active{opacity:.9}.sector-reveal-active::before,#sector-reveal.sector-reveal-active::after{animation:none;transform:translate3d(0,0,0);opacity:0}.tap-ripple{width:40px;height:40px}.tap-ripple .press-wave{animation:none;opacity:.55;transform:scale(.8)}.tap-ripple .press-spark{display:none}.gender-card,.colorchoice{transition:none}}'''
if old_reduced not in text:
    raise SystemExit('Current reduced-motion sector CSS not found.')
text = text.replace(old_reduced, new_reduced, 1)

old_js = '''let sectorRevealTimer=0,sectorRevealSequence=0;function showSectorReveal(sector){const overlay=$('sector-reveal'),reduced=window.matchMedia&&window.matchMedia('(prefers-reduced-motion: reduce)').matches,revealSector=String(sector||'').trim()||'var(--vision-teal)',sequence=++sectorRevealSequence;clearTimeout(sectorRevealTimer);overlay.style.setProperty('--reveal-sector',revealSector);overlay.classList.remove('sector-reveal-active');void overlay.offsetWidth;overlay.classList.add('sector-reveal-active');sectorRevealTimer=setTimeout(()=>{if(sequence===sectorRevealSequence)overlay.classList.remove('sector-reveal-active')},reduced?420:1450)}'''
new_js = '''let sectorRevealTimer=0,sectorRevealFrame=0,sectorRevealSequence=0;function showSectorReveal(sector){const overlay=$('sector-reveal'),reduced=window.matchMedia&&window.matchMedia('(prefers-reduced-motion: reduce)').matches,revealSector=String(sector||'').trim()||'var(--vision-teal)',sequence=++sectorRevealSequence,requestFrame=window.requestAnimationFrame?window.requestAnimationFrame.bind(window):callback=>setTimeout(callback,0);clearTimeout(sectorRevealTimer);if(sectorRevealFrame&&window.cancelAnimationFrame)window.cancelAnimationFrame(sectorRevealFrame);overlay.classList.remove('sector-reveal-active');overlay.style.setProperty('--reveal-sector',revealSector);sectorRevealFrame=requestFrame(()=>{if(sequence!==sectorRevealSequence)return;overlay.classList.add('sector-reveal-active');sectorRevealFrame=0});sectorRevealTimer=setTimeout(()=>{if(sequence===sectorRevealSequence){overlay.classList.remove('sector-reveal-active');sectorRevealFrame=0}},reduced?650:2800)}'''
if old_js not in text:
    raise SystemExit('Current sector atmosphere JavaScript not found.')
text = text.replace(old_js, new_js, 1)

path.write_text(text, encoding='utf-8')
print('Created full-screen sector vapor celebration.')
