from pathlib import Path
import re

path = Path('index.html')
text = path.read_text(encoding='utf-8')

if '/* Focused visual refinement overrides */' in text:
    raise SystemExit('Visual refinement block already exists')

css = r'''
/* Focused visual refinement overrides */
.gender-card{min-height:176px;overflow:hidden;background:linear-gradient(155deg,rgba(10,65,50,.9),rgba(2,25,19,.96));border-color:rgba(195,255,235,.31)}.gender-card::before{background:radial-gradient(circle at 50% 20%,rgba(122,244,212,.2),transparent 47%),linear-gradient(180deg,transparent,rgba(0,10,7,.28));opacity:1}.gender-card:hover{border-color:rgba(122,244,212,.9);box-shadow:0 17px 32px rgba(0,8,6,.34),0 0 18px rgba(47,214,172,.13),inset 0 1px 0 rgba(255,255,255,.15)}.gender-card.selected{border:2px solid var(--vision-teal-bright);background:linear-gradient(155deg,rgba(16,120,92,.94),rgba(3,42,32,.98));box-shadow:0 0 0 3px rgba(122,244,212,.17),0 18px 34px rgba(0,22,17,.42),0 0 27px rgba(47,214,172,.2),inset 0 1px 0 rgba(255,255,255,.2)}.gender-illustration{position:relative;z-index:1;display:block;width:102px;height:132px;color:#e7fff7;filter:drop-shadow(0 10px 12px rgba(0,0,0,.28))}.gender-illustration span{position:absolute;display:block}.gender-head{top:7px;left:35px;width:33px;height:33px;border:3px solid currentColor;border-radius:50%;background:linear-gradient(145deg,rgba(228,255,246,.5),rgba(122,244,212,.15))}.gender-neck{top:36px;left:44px;width:15px;height:17px;border-inline:3px solid currentColor}.gender-torso{top:49px;left:16px;width:70px;height:72px;border:3px solid currentColor;background:linear-gradient(180deg,rgba(122,244,212,.3),rgba(5,53,41,.4));border-radius:28px 28px 12px 12px}.gender-man .gender-torso::before{content:"";position:absolute;inset:11px 18px 0;border-inline:2px solid rgba(231,255,247,.65)}.gender-man .gender-torso::after{content:"";position:absolute;top:12px;left:31px;width:7px;height:28px;border-radius:6px;background:rgba(231,255,247,.72)}.gender-woman .gender-head{width:37px;height:37px;left:33px;top:5px}.gender-woman .gender-head::before{content:"";position:absolute;inset:-9px -8px -13px;border:4px solid currentColor;border-radius:48% 48% 44% 44%;clip-path:polygon(0 0,100% 0,100% 100%,78% 100%,78% 31%,22% 31%,22% 100%,0 100%);opacity:.9}.gender-woman .gender-torso{left:10px;width:82px;height:76px;border-radius:26px 26px 8px 8px;clip-path:polygon(27% 0,73% 0,100% 100%,0 100%)}.gender-woman .gender-torso::after{content:"";position:absolute;top:12px;left:32px;width:18px;height:26px;border:2px solid rgba(231,255,247,.72);border-radius:50% 50% 0 0;border-bottom:0}.gender-card.selected .gender-illustration{color:#fff;filter:drop-shadow(0 0 13px rgba(206,255,239,.52))}.gender-check{width:32px;height:32px;border-color:#fff;background:#b8ffe9;color:#04382c;box-shadow:0 4px 14px rgba(0,0,0,.24)}
.colorchoice{grid-template-rows:126px auto;min-height:184px}.color-copy{align-content:center;min-height:58px;padding:14px 15px}.colorname{font-size:16px}.colour-meaning,.colour-meaning-result{display:none!important}.bonus-selection-confirmation{display:flex;align-items:center;justify-content:center;gap:8px;margin:14px 0 0;color:var(--vision-teal-bright);font-size:14px;font-weight:800;line-height:1.4}.bonus-selection-confirmation::before{content:"✓";display:grid;place-items:center;width:22px;height:22px;border:1px solid rgba(184,255,233,.68);border-radius:50%;background:rgba(47,214,172,.17);color:#eafff7}.colorchoice.selected{border-color:#fff;box-shadow:0 0 0 2px var(--colour),0 14px 27px color-mix(in srgb,var(--colour),transparent 70%),inset 0 1px 0 rgba(255,255,255,.2)}
#sector-reveal{position:fixed;z-index:0;inset:-15dvh 0 0;overflow:hidden;pointer-events:none;opacity:0;--reveal-sector:var(--vision-teal)}#sector-reveal::before{content:"";position:absolute;inset:auto -18% -38dvh;height:118dvh;background:radial-gradient(ellipse at 50% 86%,color-mix(in srgb,var(--reveal-sector),transparent 52%) 0%,color-mix(in srgb,var(--reveal-sector),transparent 80%) 38%,transparent 70%);filter:blur(14px);transform:translateY(66%);opacity:0}.sector-reveal-active{opacity:1}.sector-reveal-active::before{animation:sector-glow-rise 1.05s cubic-bezier(.18,.72,.24,1) forwards}@keyframes sector-glow-rise{0%{opacity:0;transform:translateY(70%)}22%{opacity:.66}70%{opacity:.25;transform:translateY(-13%)}100%{opacity:0;transform:translateY(-25%)}}
.tap-ripple{width:46px;height:46px}.press-wave{inset:8px;border-color:rgba(160,247,218,.5);background:radial-gradient(circle,rgba(89,225,184,.17) 0 22%,rgba(47,214,172,.06) 45%,transparent 70%);animation:subtle-press-wave .54s cubic-bezier(.2,.72,.32,1) forwards}.press-flag{display:none}.press-spark{width:3px;height:3px;background:rgba(184,255,233,.65);box-shadow:0 0 7px rgba(122,244,212,.45);animation:subtle-press-spark .46s ease-out forwards}.press-spark:nth-of-type(3){top:7px;left:22px}.press-spark:nth-of-type(4){right:5px;bottom:10px;animation-delay:.05s}.press-spark:nth-of-type(5),.press-spark:nth-of-type(6){display:none}@keyframes subtle-press-wave{0%{opacity:.62;transform:scale(.38)}100%{opacity:0;transform:scale(1.12)}}@keyframes subtle-press-spark{0%{opacity:.55;transform:translate(0,0) scale(.72)}100%{opacity:0;transform:translate(calc(var(--spark-x,0)*.38),calc(var(--spark-y,-20px)*.38)) scale(1)}}
@media(max-width:600px){.gender-card{min-height:158px}.gender-illustration{transform:scale(.9)}.colorchoice{grid-template-rows:108px auto;min-height:170px}.swatch{min-height:108px}}@media(prefers-reduced-motion:reduce){#sector-reveal{inset:0;background:radial-gradient(ellipse at 50% 100%,color-mix(in srgb,var(--reveal-sector),transparent 72%),transparent 62%);transition:opacity .01ms linear}.sector-reveal-active{opacity:.85}.sector-reveal-active::before{animation:none;opacity:0}.tap-ripple{width:40px;height:40px}.tap-ripple .press-wave{animation:none;opacity:.55;transform:scale(.8)}.tap-ripple .press-spark{display:none}.gender-card,.colorchoice{transition:none}}
'''
text = text.replace('\n</style></head>', '\n' + css + '\n</style></head>', 1)
text = text.replace('<body><div id="saudi-cursor"', '<body><div id="sector-reveal" aria-hidden="true"></div><div id="saudi-cursor"', 1)

# Remove all creative colour meanings; the cards become only swatch + name.
text = re.sub(r'\n\s*const COLOUR_MEANINGS=\{.*?\};', '', text, count=1)
opts_start = text.index('const opts=q[4].map((o,i)=>')
opts_end = text.index(';const heading=', opts_start)
new_opts = '''const opts=q[4].map((o,i)=>{if(!isColourBonus)return `<button class="opt ${answers[step]===i?'selected':''}" onclick="choose(${i})" aria-pressed="${answers[step]===i}"><span class="letter">${'ABCD'[i]}</span><span>${esc(o[lang==='en'?0:1])}</span></button>`;const colour=DATA.sectors[DATA.colors[i]][2],selected=answers[step]===i;return `<button class="colorchoice ${selected?'selected':''}" style="--colour:${colour}" onclick="choose(${i})" aria-pressed="${selected}"><span class="swatch" aria-hidden="true"><span class="swatch-symbol">${selected?'✓':'✦'}</span></span><span class="color-copy"><span class="colorname">${esc(o[lang==='en'?0:1])}</span></span></button>`}).join('')'''
text = text[:opts_start] + new_opts + text[opts_end:]

# Replace the optional bonus screen content to contain only cards and the conditional confirmation.
old_bonus = "${isColourBonus?`<p class=\"small\">${L('Optional: choose a colour that feels like your leadership style. It will not change your sector result.','اختياري: اختاري لونًا يشبه أسلوب قيادتك. لن يغيّر نتيجتك في القطاعات.')}</p><div class=\"colorgrid\">${opts}</div>`:opts}"
new_bonus = "${isColourBonus?`<div class=\"colorgrid\">${opts}</div>${answers[step]===null?'':`<p class=\"bonus-selection-confirmation\" role=\"status\">${L('Selected','تم الاختيار')}</p>`}`:opts}"
if old_bonus not in text:
    raise SystemExit('Could not find bonus explanatory markup')
text = text.replace(old_bonus, new_bonus, 1)

# Keep the result colour display, but remove its former meaning line.
text = re.sub(r'<div class="colour-meaning-result">\$\{esc\(COLOUR_MEANINGS\[colour\]\[lang===\'en\'\?0:1\]\)\}</div>', '', text, count=1)

# Upgrade the icon card markup while retaining native radio semantics and no visible label copy.
pattern = r'<span class="gender-figure gender-figure-male" aria-hidden="true"><span></span><i></i></span><span class="gender-check" aria-hidden="true">✓</span><span class="sr-only">\$\{L\(\'Male\',\'ذكر\'\)\}</span></label><label class="gender-card \$\{participant\.gender===\'female\'\?\'selected\':\'\'\}"><input class="sr-only gender-input" type="radio" name="gender" value="female" \$\{participant\.gender===\'female\'\?\'checked\':\'\'\} onchange="setGender\(this\.value\)" aria-describedby="gender-error"><span class="gender-figure gender-figure-female" aria-hidden="true"><span></span><i></i></span><span class="gender-check" aria-hidden="true">✓</span><span class="sr-only">\$\{L\(\'Female\',\'أنثى\'\)\}</span>'
replacement = '''<span class="gender-illustration gender-man" aria-hidden="true"><span class="gender-head"></span><span class="gender-neck"></span><span class="gender-torso"></span></span><span class="gender-check" aria-hidden="true">✓</span><span class="sr-only">${L('Male','ذكر')}</span></label><label class="gender-card ${participant.gender==='female'?'selected':''}"><input class="sr-only gender-input" type="radio" name="gender" value="female" ${participant.gender==='female'?'checked':''} onchange="setGender(this.value)" aria-describedby="gender-error"><span class="gender-illustration gender-woman" aria-hidden="true"><span class="gender-head"></span><span class="gender-neck"></span><span class="gender-torso"></span></span><span class="gender-check" aria-hidden="true">✓</span><span class="sr-only">${L('Female','أنثى')}</span>'''
text, count = re.subn(pattern, replacement, text, count=1)
if count != 1:
    raise SystemExit('Could not replace gender illustration markup')

# Add sector page glow activation while preserving all established ARIA and focus steps.
old_reveal = "function revealMatch(rank){if(revealedMatches[rank])return;revealedMatches[rank]=true;const card=document.querySelector(`[data-match-rank=\"${rank}\"]`),back=card.querySelector('.match-card-back'),front=card.querySelector('.match-card-front'),button=back,status=$('match-status');front.removeAttribute('inert');front.removeAttribute('aria-hidden');button.setAttribute('aria-expanded','true');card.classList.add('is-revealed');back.setAttribute('inert','');back.setAttribute('aria-hidden','true');if(status)status.textContent=rank===1?L('Your main sector match is revealed.','تم الكشف عن مطابقتك الأولى في القطاع.'):L('Your second-best sector match is revealed.','تم الكشف عن مطابقتك الثانية الأفضل في القطاع.');setTimeout(()=>{const heading=front.querySelector('h2');if(heading&&heading.isConnected)heading.focus({preventScroll:true});if(revealedMatches[1]&&revealedMatches[2])render()},window.matchMedia&&window.matchMedia('(prefers-reduced-motion: reduce)').matches?0:620)}"
new_reveal = "let sectorRevealTimer=0;function showSectorReveal(sector){const overlay=$('sector-reveal'),reduced=window.matchMedia&&window.matchMedia('(prefers-reduced-motion: reduce)').matches;clearTimeout(sectorRevealTimer);overlay.style.setProperty('--reveal-sector',sector);overlay.classList.remove('sector-reveal-active');void overlay.offsetWidth;overlay.classList.add('sector-reveal-active');sectorRevealTimer=setTimeout(()=>overlay.classList.remove('sector-reveal-active'),reduced?300:1120)}\n\tfunction revealMatch(rank){if(revealedMatches[rank])return;revealedMatches[rank]=true;const card=document.querySelector(`[data-match-rank=\"${rank}\"]`),back=card.querySelector('.match-card-back'),front=card.querySelector('.match-card-front'),button=back,status=$('match-status');front.removeAttribute('inert');front.removeAttribute('aria-hidden');button.setAttribute('aria-expanded','true');card.classList.add('is-revealed');back.setAttribute('inert','');back.setAttribute('aria-hidden','true');showSectorReveal(card.style.getPropertyValue('--sector'));if(status)status.textContent=rank===1?L('Your main sector match is revealed.','تم الكشف عن مطابقتك الأولى في القطاع.'):L('Your second-best sector match is revealed.','تم الكشف عن مطابقتك الثانية الأفضل في القطاع.');setTimeout(()=>{const heading=front.querySelector('h2');if(heading&&heading.isConnected)heading.focus({preventScroll:true});if(revealedMatches[1]&&revealedMatches[2])render()},window.matchMedia&&window.matchMedia('(prefers-reduced-motion: reduce)').matches?0:620)}"
if old_reveal not in text:
    raise SystemExit('Could not find reveal function')
text = text.replace(old_reveal, new_reveal, 1)

# Use only a small, soft pair of flecks with the shimmer ring.
old_effect = "ripple.innerHTML='<span class=\"press-wave\"></span><span class=\"press-flag\"></span><i class=\"press-spark\" style=\"--spark-x:-18px;--spark-y:-23px\"></i><i class=\"press-spark\" style=\"--spark-x:21px;--spark-y:-8px\"></i><i class=\"press-spark\" style=\"--spark-x:15px;--spark-y:18px\"></i><i class=\"press-spark\" style=\"--spark-x:-15px;--spark-y:15px\"></i>';"
new_effect = "ripple.innerHTML='<span class=\"press-wave\"></span><i class=\"press-spark\" style=\"--spark-x:-12px;--spark-y:-14px\"></i><i class=\"press-spark\" style=\"--spark-x:13px;--spark-y:8px\"></i>';"
if old_effect not in text:
    raise SystemExit('Could not find press effect markup')
text = text.replace(old_effect, new_effect, 1)

path.write_text(text, encoding='utf-8')
print('Applied focused visual refinements.')
